site_name: project pancake 
site_url: https://docs.trousseau.io

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - git-committers:
      repository: trousseau-io/docs.trousseau.io
      branch: main 
#       token: !ENV GH_TOKEN

theme:
  font:
    text: Red Hat Text
    code: Red Hat Mono
  features:
    - content.code.annotate
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  name: material
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to system preference
extra_css: 
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/romdalf/project-pancake
  generator: true
copyright: Apache-2.0 License. 
repo_url: https://github.com/romdalf/project-pancake 
repo_name: romdalf/project-pancake
edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - def_list
  - md_in_html
  - pymdownx.snippets:
      base_path: 'docs/'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - About: 'index.md'
  - Release Notes: 'releases.md'
  - Architecture:
    - Concepts: 'concepts.md' 
    - Architecture: 'architecture.md'
  - Deploying:
    - Requirements: 'bom.md'
    - Hardware Build: 'hardware.md' 
    - Software Buidl: 'software.md'
    - Operating: 'ops.md' 
  - Contributing: 
    - Guidelines: 'CONTRIBUTING.md'
    - Development: 'devenv.md'
  - Reference: 'community.md'
  - Support: 'support.md'